In [1]:
import pandas as pd
import numpy as np

In [26]:
bingo = np.loadtxt('input.txt', delimiter=",", dtype=np.int_, max_rows=1)
bingo


array([15, 61, 32, 33, 87, 17, 56, 73, 27, 83,  0, 18, 43,  8, 86, 37, 40,
        6, 93, 25, 14, 68, 64, 57, 39, 46, 55, 13, 21, 72, 51, 81, 78, 79,
       52, 65, 36, 92, 97, 28,  9, 24, 22, 69, 70, 42,  3,  4, 63, 50, 91,
       16, 41, 94, 77, 85, 49, 12, 76, 67, 11, 62, 99, 54, 95,  1, 74, 34,
       88, 89, 82, 48, 84, 98, 58, 44,  5, 53,  7, 19, 29, 30, 35, 26, 31,
       10, 60, 59, 80, 71, 45, 38, 20, 66, 47,  2, 23, 96, 90, 75])

In [79]:
boards = pd.read_csv('input.txt', sep=" +", lineterminator='\n', header=None, skiprows=2).to_numpy()
boards = boards.reshape((100, 5, 5))
boards

C:\Users\giach\anaconda3\envs\ml\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


array([[[26, 68,  3, 95, 59],
        [40, 88, 50, 22, 48],
        [75, 67,  8, 64,  6],
        [29,  2, 73, 78,  5],
        [49, 25, 80, 89, 96]],

       [[57, 26, 21, 56, 70],
        [38, 48, 78, 40, 54],
        [82, 71, 22, 24,  4],
        [16,  9, 65, 42, 79],
        [43, 94, 39, 12, 67]],

       [[70, 97, 26, 39, 22],
        [65, 11, 69,  6, 93],
        [71, 74, 72, 57, 59],
        [61, 21, 89, 86, 17],
        [66, 15, 94, 79, 85]],

       ...,

       [[ 3, 68, 80, 19, 59],
        [41,  6, 92, 58, 28],
        [94, 57, 81,  5, 71],
        [90, 54,  9,  8, 14],
        [32, 96, 30, 37, 10]],

       [[15, 16, 14, 10, 52],
        [51, 26, 54, 24, 84],
        [45, 90, 28, 36, 96],
        [56, 70, 86, 94, 32],
        [67, 81, 13, 29, 27]],

       [[67, 30, 89, 43,  3],
        [86, 10, 38, 90, 77],
        [70, 78, 97, 94, 33],
        [29,  8, 85, 69, 56],
        [40, 80, 47, 12, 17]]], dtype=int64)

In [80]:
winner_number, winner_idx = None, None

copy_boards = np.copy(boards)

for number in bingo:
    indices = np.where(copy_boards == number)
    copy_boards[indices] = -1
    column_sums = np.sum(copy_boards, axis=1)
    row_sums = np.sum(copy_boards, axis=2)
    row_winner = np.where(row_sums == -5)
    column_winner = np.where(column_sums == -5)

    if len(row_winner[0]) != 0:
        winner_idx = row_winner[0][0]
        winner_number = number
        break
    elif len(column_winner[0]) != 0:
        winner_idx = column_winner[0][0]
        winner_number = number
        break

winner = copy_boards[winner_idx, :, :]
winner

array([[-1, 69,  3, 45, 94],
       [-1, 90, -1, 95, 48],
       [-1,  9,  2, 74, 59],
       [-1, 46, -1, 98, -1],
       [-1, -1, 24, 31, 72]], dtype=int64)

In [81]:
winner[winner==-1] = 0
winner_sum = np.sum(winner)
winner_sum*winner_number

58412

In [92]:
loser_number = None
copy_boards = np.copy(boards)

for number in bingo:
    indices = np.where(copy_boards == number)
    copy_boards[indices] = -1
    column_sums = np.sum(copy_boards, axis=1)
    row_sums = np.sum(copy_boards, axis=2)
    row_winner = np.where(row_sums == -5)
    column_winner = np.where(column_sums == -5)

    if copy_boards.shape[0] != 1:
        winner_idx = np.concatenate((row_winner[0], column_winner[0]))
        copy_boards = np.delete(copy_boards, winner_idx, axis=0)
    elif len(row_winner[0]) != 0 or len(column_winner[0]) != 0:
            loser_number = number
            break

loser = copy_boards[0, :, :]
loser

array([[-1, -1, -1, -1, -1],
       [80, -1, -1, -1, -1],
       [-1, -1, -1, 45, -1],
       [-1,  2, -1, -1, -1],
       [20, -1, -1, -1, 23]], dtype=int64)

In [93]:
loser[loser==-1] = 0
loser_sum = np.sum(loser)
loser_sum*loser_number

10030