In [4]:
import pandas as pd
import numpy as np

In [8]:
instr = pd.read_csv('input.txt', sep=",| -> ", lineterminator='\n', header=None)
print(instr.head())

     0    1    2    3
0  692  826  692  915
1  914  338  524  728
2   77  505   77  912
3   31  484  250  703
4   29  241  313  241


C:\Users\giach\anaconda3\envs\ml\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [9]:
instr = instr.to_numpy()
instr.shape

(500, 4)

In [13]:
limit = np.max(instr)
limit

989

In [38]:
vents = np.zeros((limit+1, limit+1), dtype=np.int_)
vents.shape

(990, 990)

In [39]:
for line in instr:
    if line[0] == line[2]:
        if line[1] < line[3]:
            vents[line[0], line[1]:line[3]+1] += 1
        else:
            vents[line[0], line[3]:line[1]+1] += 1
    elif line[1] == line[3]:
        if line[0] < line[2]:
            vents[line[0]:line[2]+1, line[1]] += 1
        else:
            vents[line[2]:line[0]+1, line[1]] += 1

vents

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
len(np.where(vents > 1)[0])

5698

In [53]:
vents = np.zeros((limit+1, limit+1), dtype=np.int_)
vents.shape

(990, 990)

In [48]:
idx_row = np.linspace(0, 3, 3-0+1, dtype=np.int_)
idx_row

array([0, 1, 2, 3])

In [49]:
idx_col = np.linspace(1, 4, 4-1+1, dtype=np.int_)
idx_col

array([1, 2, 3, 4])

In [52]:
vents[(idx_row, idx_col)] += 1
vents[:10, :10]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [54]:
for line in instr:
    if line[0] == line[2]:
        if line[1] < line[3]:
            vents[line[0], line[1]:line[3]+1] += 1
        else:
            vents[line[0], line[3]:line[1]+1] += 1
    elif line[1] == line[3]:
        if line[0] < line[2]:
            vents[line[0]:line[2]+1, line[1]] += 1
        else:
            vents[line[2]:line[0]+1, line[1]] += 1
    else:
        if line[2] > line[0]:
            idx_row = np.linspace(line[0], line[2], line[2] - line[0] + 1, dtype=np.int_)
        else:
            idx_row = np.flip(np.linspace(line[2], line[0], line[0] - line[2] + 1, dtype=np.int_))

        if line[1] > line[3]:
            idx_col = np.flip(np.linspace(line[3], line[1], line[1] - line[3] + 1, dtype=np.int_))
        else:
            idx_col = np.linspace(line[1], line[3], line[3] - line[1] + 1, dtype=np.int_)

        vents[(idx_row, idx_col)] += 1

vents

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [55]:
len(np.where(vents > 1)[0])

15463